name: Cypress-Cucumber
on:
    push:
        branches: [master]
jobs:
    Run_test:
        runs-on: windows-latest
        strategy:
            matrix:
                node-version: [14.17.0]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: install all dependencies
              run: npm install
            - name: run test
              run: npm run cypress:run
            - name: Generate reports
              if: always()
              run: npm run cypress:report
            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: cucumber-report
                  path: ./reports/cucumber-htmlreport
                  retention-days: 5 
            - name: Deploy to gh-pages
              if: always()
              uses: peaceiris/actions-gh-pages@v3.7.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: reports/cucumber-htmlreport/
